CREATE sharded TABLE CUSTOMER ( 
       C_CUSTKEY        NUMBER NOT NULL,
       C_NAME           VARCHAR2(25) NOT NULL,
       C_ADDRESS        VARCHAR2(40) NOT NULL,
       C_NATIONKEY      NUMBER NOT NULL,
       C_PHONE          VARCHAR2(15) NOT NULL,
       C_ACCTBAL        NUMBER NOT NULL,
       C_MKTSEGMENT     VARCHAR2(10) NOT NULL,
       C_COMMENT        VARCHAR2(117) NOT NULL,
       CONSTRAINT CUSTOMERPK  PRIMARY KEY (C_CUSTKEY)
);

CREATE sharded TABLE ORDERS  ( 
       O_ORDERKEY       NUMBER NOT NULL,
       O_CUSTKEY        NUMBER NOT NULL,
       O_ORDERSTATUS    CHAR(1) NOT NULL,
       O_TOTALPRICE     NUMBER  NOT NULL,
       O_ORDERDATE      DATE NOT NULL,
       O_ORDERPRIORITY  VARCHAR2(15) NOT NULL,  
       O_CLERK          VARCHAR2(15) NOT NULL, 
       O_SHIPPRIORITY   NUMBER  NOT NULL,
       O_COMMENT        VARCHAR2(79) NOT NULL,
       CONSTRAINT O_ORDERKEY_PK PRIMARY KEY (O_CUSTKEY, O_ORDERKEY),
	   CONSTRAINT ORDERSFK FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER (C_CUSTKEY)
);

CREATE sharded TABLE LINEITEM ( 
       L_ORDERKEY       NUMBER NOT NULL,
       L_CUSTKEY        NUMBER  NOT NULL,
       L_PARTKEY        NUMBER NOT NULL,
       L_SUPPKEY        NUMBER NOT NULL,
       L_LINENUMBER     NUMBER NOT NULL,
       L_QUANTITY       NUMBER  NOT NULL,
       L_EXTENDEDPRICE  NUMBER  NOT NULL,
       L_DISCOUNT       NUMBER  NOT NULL,
       L_TAX            NUMBER  NOT NULL,
       L_RETURNFLAG     CHAR(1) NOT NULL,
       L_LINESTATUS     CHAR(1) NOT NULL,
       L_SHIPDATE       DATE NOT NULL,
       L_COMMITDATE     DATE NOT NULL,
       L_RECEIPTDATE    DATE NOT NULL,
       L_SHIPINSTRUCT   VARCHAR2(25) NOT NULL,
       L_SHIPMODE       VARCHAR2(10) NOT NULL,
       L_COMMENT        VARCHAR2(50) NOT NULL,
       CONSTRAINT ORDER_LINE_PK PRIMARY KEY (L_CUSTKEY, L_ORDERKEY,L_LINENUMBER),
       CONSTRAINT L_ORDERKEY_FK FOREIGN KEY (L_CUSTKEY, L_ORDERKEY) references ORDERS (O_CUSTKEY, O_ORDERKEY)
);

CREATE duplicated TABLE REGION  ( 
       R_REGIONKEY      NUMBER NOT NULL,
       R_NAME           VARCHAR2(25) NOT NULL,
       R_COMMENT        VARCHAR2(152),
       CONSTRAINT REGIONPK  PRIMARY KEY (R_REGIONKEY)
);
        
CREATE duplicated TABLE NATION  ( 
       N_NATIONKEY      NUMBER NOT NULL,
       N_NAME           VARCHAR2(25) NOT NULL,
       N_REGIONKEY      NUMBER NOT NULL,
       N_COMMENT        VARCHAR2(152),
       CONSTRAINT NATIONPK  PRIMARY KEY (N_NATIONKEY)
);

CREATE duplicated TABLE PART  ( 
       P_PARTKEY        NUMBER NOT NULL,
       P_NAME           VARCHAR2(55) NOT NULL,
       P_MFGR           VARCHAR2(25) NOT NULL,
       P_BRAND          VARCHAR2(10) NOT NULL,
       P_TYPE           VARCHAR2(25) NOT NULL,
       P_SIZE           NUMBER NOT NULL,
       P_CONTAINER      VARCHAR2(10) NOT NULL,
       P_RETAILPRICE    NUMBER NOT NULL,
       P_COMMENT        VARCHAR2(23) NOT NULL,
       CONSTRAINT PARTPK  PRIMARY KEY (P_PARTKEY)
);

CREATE duplicated TABLE SUPPLIER ( 
       S_SUPPKEY        NUMBER NOT NULL,
       S_NAME           VARCHAR2(25) NOT NULL,
       S_ADDRESS        VARCHAR2(40) NOT NULL,
       S_NATIONKEY      NUMBER NOT NULL,
       S_PHONE          VARCHAR2(15) NOT NULL,
       S_ACCTBAL        NUMBER NOT NULL,
       S_COMMENT        VARCHAR2(101) NOT NULL,
       CONSTRAINT SUPPLIERPK  PRIMARY KEY (S_SUPPKEY)
); 

CREATE duplicated TABLE PARTSUPP ( 
       PS_PARTKEY       NUMBER NOT NULL,
       PS_SUPPKEY       NUMBER NOT NULL,
       PS_AVAILQTY      NUMBER NOT NULL,
       PS_SUPPLYCOST    NUMBER NOT NULL,
       PS_COMMENT       VARCHAR2(199) NOT NULL,
       CONSTRAINT PARTSUPPPK  PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
); 
